# Generated by Django 5.0 on 2025-02-15 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="enrolledgroups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
