# Generated by Django 5.0 on 2025-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0002_alter_group_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
