# Generated by Django 5.0 on 2025-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0003_group_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
