# Generated by Django 5.0 on 2025-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0004_alter_group_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
