# Generated by Django 5.0 on 2025-02-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0008_alter_groupbalance_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbalance",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
