# Generated by Django 5.0 on 2025-02-25 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0011_group_slug_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="groupbalance",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="split.group"
            ),
        ),
    ]
