# Generated by Django 5.0 on 2025-03-10 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0014_split"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="split",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_expenses",
                to="split.group",
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="expense",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="split",
                to="split.expense",
            ),
        ),
    ]
