# Generated by Django 5.0 on 2025-03-10 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0015_alter_split_unique_together_alter_expense_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="split",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="split",
                to="split.expense",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="split",
            unique_together={("user", "expense")},
        ),
    ]
