# Generated by Django 5.0 on 2025-03-11 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0016_alter_split_expense_alter_split_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at"]},
        ),
    ]
