# Generated by Django 5.0 on 2025-03-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0017_alter_expense_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbalance",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupbalancesg",
                to="split.group",
            ),
        ),
    ]
