# Generated by Django 5.0 on 2025-03-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0019_groupbalance_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="split",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="split.expense",
            ),
        ),
    ]
