# Generated by Django 5.0 on 2025-03-18 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0020_alter_split_expense"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbalance",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_balances",
                to="split.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupbalance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group_balance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
