# Generated by Django 5.0 on 2025-03-18 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0022_alter_groupbalance_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupbalance",
            unique_together={("user", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="split",
            unique_together={("user", "expense")},
        ),
    ]
