# Generated by Django 5.0 on 2025-03-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0023_alter_groupbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbalance',
            options={'ordering': ['-modified'], 'verbose_name': 'Group Balance'},
        ),
    ]
