# Generated by Django 5.0 on 2025-03-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0024_alter_groupbalance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbalance',
            options={'ordering': ['-modified', '-group__modified'], 'verbose_name': 'Group Balance'},
        ),
    ]
