# Generated by Django 5.0 on 2025-03-26 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0026_settle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settle',
            new_name='Settlement',
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name_plural': 'Settle'},
        ),
    ]
