# Generated by Django 5.0 on 2025-03-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0027_rename_settle_settlement_alter_settlement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlement',
            options={},
        ),
    ]
