# Generated by Django 5.0 on 2025-03-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("split", "0028_alter_settlement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_settlements",
                to="split.group",
            ),
            preserve_default=False,
        ),
    ]
