# Generated by Django 5.0 on 2025-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0030_alter_groupbalance_options_split_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='split',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
